version: "3"

services:
  etcd:
    environment:
      HostIP: 127.0.0.1
    container_name: etcd-grpc-demo
    image: quay.io/coreos/etcd:v2.3.8
    command: -name etcd0 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -initial-advertise-peer-urls http://127.0.0.1:12380 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd0=http://127.0.0.1:12380" -initial-cluster-state new
    ports:
    - 14001:4001
    - 12380:2380
    - 12379:2379
