// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cli/hello.proto

package hello

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg struct {
	Val                  string   `protobuf:"bytes,1,opt,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdf6837146bf8c6e, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type MsgResp struct {
	Val                  string   `protobuf:"bytes,1,opt,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgResp) Reset()         { *m = MsgResp{} }
func (m *MsgResp) String() string { return proto.CompactTextString(m) }
func (*MsgResp) ProtoMessage()    {}
func (*MsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdf6837146bf8c6e, []int{1}
}

func (m *MsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResp.Unmarshal(m, b)
}
func (m *MsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResp.Marshal(b, m, deterministic)
}
func (m *MsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResp.Merge(m, src)
}
func (m *MsgResp) XXX_Size() int {
	return xxx_messageInfo_MsgResp.Size(m)
}
func (m *MsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResp proto.InternalMessageInfo

func (m *MsgResp) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "Msg")
	proto.RegisterType((*MsgResp)(nil), "MsgResp")
}

func init() { proto.RegisterFile("cli/hello.proto", fileDescriptor_fdf6837146bf8c6e) }

var fileDescriptor_fdf6837146bf8c6e = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xc9, 0xd4,
	0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x12, 0xe7, 0x62, 0xf6,
	0x2d, 0x4e, 0x17, 0x12, 0xe0, 0x62, 0x0e, 0x4b, 0xcc, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0x31, 0x95, 0xa4, 0xb9, 0xd8, 0x7d, 0x8b, 0xd3, 0x83, 0x52, 0x8b, 0x0b, 0x30, 0x25, 0x8d,
	0xe4, 0xb8, 0x58, 0x3d, 0x40, 0x86, 0x08, 0x89, 0x72, 0x31, 0x07, 0x27, 0x56, 0x0a, 0xb1, 0xe8,
	0xf9, 0x16, 0xa7, 0x4b, 0x71, 0xe8, 0x41, 0x75, 0x24, 0xb1, 0x81, 0x0d, 0x37, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xf6, 0xea, 0x89, 0xf0, 0x6f, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	Say(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*MsgResp, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Say(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*MsgResp, error) {
	out := new(MsgResp)
	err := c.cc.Invoke(ctx, "/Hello/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	Say(context.Context, *Msg) (*MsgResp, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) Say(ctx context.Context, req *Msg) (*MsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hello/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Say(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Hello_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cli/hello.proto",
}
