version: "3"

services:
  prom-demo:
    image: prom/prometheus:latest
    container_name: prom-demo
    volumes:
    - /Users/wzy/projects/godie/src/github.com/ojbkgo/grpc-demo/module/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9000
      - 9090
    depends_on:
      - consul
    ports:
    - 9090:9090

  grafana:
    image: grafana/grafana:7.0.3
    expose:
      - 3000
    depends_on:
      - prom-demo
      - consul
    ports:
      - 3000:3000

  consul:
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: 'eth0'
    ports:
      - 8500:8500
    command: [
      "agent",
      "-server",
      "-bootstrap",
      "-ui",
      "-node=1",
      "-client=0.0.0.0"
    ]